AllCops:
  Exclude:
    - 'toy_robot.gemspec'
    - 'vendor/**/*'
  DisplayCopNames: true

Style/MutableConstant:
  Enabled: false

Style/SignalException:
  Enabled: false

Metrics/LineLength:
  Max: 150
